---
title: "replication_paper_result"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{replication_paper_result}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


# Joint Tests generating RDatas null coverage
```{r Joint Test Run null coverage}
rm(list = ls())
library(tictoc)
library(rdtest)
library(gt)
library(ggplot2)
library(dplyr)
library(truncnorm)

fun.runnerJoint = function(str.spec)
{
  message(str.spec)
  #tic(str.spec)
  time.start <- Sys.time()
  eval(parse(text = paste0(paste0("list.summary <- rdtest::return_result_MC_joint(",str.spec),")")))
  time.end <- Sys.time()
  #toc()
  message((time.end - time.start)," min")
  return(list.summary)
}

# Specification list
# values for x jumps
vec.xJump <- c(0) #,0.15,0.3)
# values for z jumps
vec.zJump <- c(0) #seq(0,2,length=5)
# sample sizes
vec.n <- c(500,1000)
vec.covZ <- c(0,0.5,0.9)
vec.dimZ <- c(1,3,5,10,25)
# the last one, half, full:
## half: for 3, 2:3 jumps.
vec.frac_jump <- list("'None'") #list("'Last'","'Half'","'All'")

int.numberSpec <- length(vec.xJump)*length(vec.n)*length(vec.zJump)*length(vec.covZ)*length(vec.dimZ)*length(vec.frac_jump)#*3

vec.effNzReportSpec <- c(1:int.numberSpec)
vec.effNxReportSpec <- c(1:int.numberSpec)
vec.corZReportSpec <- c(1:int.numberSpec)
vec.dimVecReportSpec <- c(1:int.numberSpec)
vec.nReportSpec <- c(1:int.numberSpec)
vec.xjumpReportSpec <- c(1:int.numberSpec)
vec.zjumpReportSpec <- c(1:int.numberSpec)
vec.naiveReportResult <- c(1:int.numberSpec)
vec.bonfeReportResult <- c(1:int.numberSpec)
vec.jointReportResult <- c(1:int.numberSpec)
vec.maxTestSpec <- c(1:int.numberSpec)
vec.avgMaxTestCritical <- c(1:int.numberSpec)
vec.medianMaxTestCritical <- c(1:int.numberSpec)
vec.jumpTestSpec <- c(1:int.numberSpec)

list.speclist <- list()

counter <- 1
df.resultJointTest <- data.frame()
fun.repeaterJoint <- function(n,cov_z,dim,x_jump,z_jump,bool_max_test,bool_L2_std = FALSE,counter,df.resultJointTest,frac_jump,spec) {
    list.sum <- fun.runnerJoint(str.spec=spec)

    real.effNzReportSpec <- round(list.sum$effN.mean,1)
    real.effNxReportSpec <- round(list.sum$effNx.mean,1)
    real.corZReportSpec <- round(list.sum$cor.z,2)
    real.dimVecReportSpec <- dim
    real.nReportSpec <- n
    real.xjumpReportSpec <- x_jump
    real.zjumpReportSpec <- z_jump

    real.naiveReportResult <- round(list.sum$naive,3)
    real.bonfeReportResult <- round(list.sum$bonfe,3)
    real.jointReportResult <- round(list.sum$joint,3)
    real.maxTestSpec <- bool_max_test
    if (bool_max_test) {
      real.avgMaxTestCritical <- round(mean(list.sum$maxCritical),3)
      real.medianMaxTestCritical <- round(median(list.sum$maxCritical),3)
    } else {
      real.avgMaxTestCritical <- NA
      real.medianMaxTestCritical <- NA
    }

    list.speclist[counter] <- spec
    #print(spec)

    df.resultJointTest <- rbind(df.resultJointTest,
                                 data.frame(vec.effNzReportSpec = real.effNzReportSpec,
                                 vec.effNxReportSpec = real.effNxReportSpec,
                                 vec.corZReportSpec = cov_z,
                                 vec.dimVecReportSpec = real.dimVecReportSpec,
                                 vec.nReportSpec = real.nReportSpec,
                                 vec.xjumpReportSpec = real.xjumpReportSpec,
                                 vec.zjumpReportSpec = real.zjumpReportSpec,
                                 vec.naiveReportResult = real.naiveReportResult,
                                 vec.bonfeReportResult = real.bonfeReportResult,
                                 vec.jointReportResult = real.jointReportResult,
                                 vec.maxTestSpec = real.maxTestSpec,
                                 vec.chisqStd = bool_L2_std,
                                 vec.avgMaxTestCritical = real.avgMaxTestCritical,
                                 vec.medianMaxTestCritical = real.medianMaxTestCritical,
                                 vec.jumpTestSpec = frac_jump))
    return(df.resultJointTest)
}

#
# UNDO COMMENT OUT TO RE-GENERATE THE RESULTS
#
for (n in vec.n) {
  for (dim in vec.dimZ) {
    if (dim == 1) {
      vec.covZUsed <- c(0)
    } else {
      vec.covZUsed <- vec.covZ
    }
    for (cov_z in vec.covZUsed) {
      for (frac_jump in vec.frac_jump) {
        cat("Running for n=",n,",dim=",dim,",cov_z=",cov_z,",frac=", frac_jump,".\n")
        # bool_max_test TRUE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",TRUE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = TRUE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec)
                counter <- counter + 1
            }
          }
        }
        # bool_max_test FALSE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",FALSE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = FALSE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec)
                counter <- counter + 1
            }
          }
        }
        # bool_max_test FALSE, bool_L2_std TRUE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",FALSE,",bool_L2_std=",TRUE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = FALSE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec,bool_L2_std=TRUE)
                counter <- counter + 1
            }
          }
        }
      }
    }

  }
  if (n == 500) {
    save.image("./workSpaceMCJointTest_full_coverage_n500.RData")
    df.coverage <- data.frame(n=df.resultJointTest[,5],cov=df.resultJointTest[,3],dim=df.resultJointTest[,4],p.naive=df.resultJointTest[,8],p.bonferroni=df.resultJointTest[,9],p.joint=df.resultJointTest[,10],isMaxTest=df.resultJointTest[,11],isChiStd=df.resultJointTest[,12])
  print(df.coverage %>% gt())
    df.resultJointTest <- data.frame()
  }
}
df.coverage <- data.frame(n=df.resultJointTest[,5],cov=df.resultJointTest[,3],dim=df.resultJointTest[,4],p.naive=df.resultJointTest[,8],p.bonferroni=df.resultJointTest[,9],p.joint=df.resultJointTest[,10],isMaxTest=df.resultJointTest[,11],isChiStd=df.resultJointTest[,12])
save.image("./workSpaceMCJointTest_full_coverage_n1000.RData")
print(df.coverage %>% gt())

```

# Joint Tests generating RDatas null coverage: additional for dim = 1
```{r Joint Test Run null coverage additional for dim 1}
rm(list = ls())
library(tictoc)
library(rdtest)
library(gt)
library(ggplot2)
library(dplyr)
library(truncnorm)

fun.runnerJoint = function(str.spec)
{
  message(str.spec)
  #tic(str.spec)
  time.start <- Sys.time()
  eval(parse(text = paste0(paste0("list.summary <- rdtest::return_result_MC_joint(",str.spec),")")))
  time.end <- Sys.time()
  #toc()
  message((time.end - time.start)," min")
  return(list.summary)
}

# Specification list
# values for x jumps
vec.xJump <- c(0) #,0.15,0.3)
# values for z jumps
vec.zJump <- c(0) #seq(0,2,length=5)
# sample sizes
vec.n <- c(500,1000)
vec.covZ <- c(0,0.5)
vec.dimZ <- c(1)
# the last one, half, full:
## half: for 3, 2:3 jumps.
vec.frac_jump <- list("'None'") #list("'Last'","'Half'","'All'")

int.numberSpec <- length(vec.xJump)*length(vec.n)*length(vec.zJump)*length(vec.covZ)*length(vec.dimZ)*length(vec.frac_jump)#*3

vec.effNzReportSpec <- c(1:int.numberSpec)
vec.effNxReportSpec <- c(1:int.numberSpec)
vec.corZReportSpec <- c(1:int.numberSpec)
vec.dimVecReportSpec <- c(1:int.numberSpec)
vec.nReportSpec <- c(1:int.numberSpec)
vec.xjumpReportSpec <- c(1:int.numberSpec)
vec.zjumpReportSpec <- c(1:int.numberSpec)
vec.naiveReportResult <- c(1:int.numberSpec)
vec.bonfeReportResult <- c(1:int.numberSpec)
vec.jointReportResult <- c(1:int.numberSpec)
vec.maxTestSpec <- c(1:int.numberSpec)
vec.avgMaxTestCritical <- c(1:int.numberSpec)
vec.medianMaxTestCritical <- c(1:int.numberSpec)
vec.jumpTestSpec <- c(1:int.numberSpec)

list.speclist <- list()

counter <- 1
df.resultJointTest <- data.frame()
fun.repeaterJoint <- function(n,cov_z,dim,x_jump,z_jump,bool_max_test,bool_L2_std = FALSE,counter,df.resultJointTest,frac_jump,spec) {
    list.sum <- fun.runnerJoint(str.spec=spec)

    real.effNzReportSpec <- round(list.sum$effN.mean,1)
    real.effNxReportSpec <- round(list.sum$effNx.mean,1)
    real.corZReportSpec <- round(list.sum$cor.z,2)
    real.dimVecReportSpec <- dim
    real.nReportSpec <- n
    real.xjumpReportSpec <- x_jump
    real.zjumpReportSpec <- z_jump

    real.naiveReportResult <- round(list.sum$naive,3)
    real.bonfeReportResult <- round(list.sum$bonfe,3)
    real.jointReportResult <- round(list.sum$joint,3)
    real.maxTestSpec <- bool_max_test
    if (bool_max_test) {
      real.avgMaxTestCritical <- round(mean(list.sum$maxCritical),3)
      real.medianMaxTestCritical <- round(median(list.sum$maxCritical),3)
    } else {
      real.avgMaxTestCritical <- NA
      real.medianMaxTestCritical <- NA
    }

    list.speclist[counter] <- spec
    #print(spec)

    df.resultJointTest <- rbind(df.resultJointTest,
                                 data.frame(vec.effNzReportSpec = real.effNzReportSpec,
                                 vec.effNxReportSpec = real.effNxReportSpec,
                                 vec.corZReportSpec = cov_z,
                                 vec.dimVecReportSpec = real.dimVecReportSpec,
                                 vec.nReportSpec = real.nReportSpec,
                                 vec.xjumpReportSpec = real.xjumpReportSpec,
                                 vec.zjumpReportSpec = real.zjumpReportSpec,
                                 vec.naiveReportResult = real.naiveReportResult,
                                 vec.bonfeReportResult = real.bonfeReportResult,
                                 vec.jointReportResult = real.jointReportResult,
                                 vec.maxTestSpec = real.maxTestSpec,
                                 vec.chisqStd = bool_L2_std,
                                 vec.avgMaxTestCritical = real.avgMaxTestCritical,
                                 vec.medianMaxTestCritical = real.medianMaxTestCritical,
                                 vec.jumpTestSpec = frac_jump))
    return(df.resultJointTest)
}

#
# UNDO COMMENT OUT TO RE-GENERATE THE RESULTS
#
# 
for (n in vec.n) {
  for (dim in vec.dimZ) {

    vec.covZUsed <- vec.covZ
    for (cov_z in vec.covZUsed) {
      for (frac_jump in vec.frac_jump) {
        cat("Running for n=",n,",dim=",dim,",cov_z=",cov_z,",frac=", frac_jump,".\n")
        # bool_max_test TRUE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",TRUE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = TRUE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec)
                counter <- counter + 1
            }
          }
        }
        # bool_max_test FALSE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",FALSE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = FALSE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec)
                counter <- counter + 1
            }
          }
        }
        # bool_max_test FALSE, bool_L2_std TRUE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",FALSE,",bool_L2_std=",TRUE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = FALSE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec,bool_L2_std=TRUE)
                counter <- counter + 1
            }
          }
        }
      }
    }

  }
  if (n == 500) {
    df.coverage <- data.frame(n=df.resultJointTest[,5],cov=df.resultJointTest[,3],dim=df.resultJointTest[,4],p.naive=df.resultJointTest[,8],p.bonferroni=df.resultJointTest[,9],p.joint=df.resultJointTest[,10],isMaxTest=df.resultJointTest[,11],isChiStd=df.resultJointTest[,12])
    save.image("./workSpaceMCJointTest_full_coverage_n500_dim1.RData")
  print(df.coverage %>% gt())
    df.resultJointTest <- data.frame()
  }
}
df.coverage <- data.frame(n=df.resultJointTest[,5],cov=df.resultJointTest[,3],dim=df.resultJointTest[,4],p.naive=df.resultJointTest[,8],p.bonferroni=df.resultJointTest[,9],p.joint=df.resultJointTest[,10],isMaxTest=df.resultJointTest[,11],isChiStd=df.resultJointTest[,12])
save.image("./workSpaceMCJointTest_full_coverage_n1000_dim1.RData")
print(df.coverage %>% gt())

```

```{r coverage table}
rm(list = ls())
load("./workSpaceMCJointTest_full_coverage_n500.RData")
df.resultJointTest <- df.resultJointTest[df.resultJointTest$vec.xjumpReportSpec == 0,]
df.coverage <- data.frame(n=df.resultJointTest[,5],cov=df.resultJointTest[,3],dim=df.resultJointTest[,4],p.naive=df.resultJointTest[,8],p.bonferroni=df.resultJointTest[,9],p.joint=df.resultJointTest[,10],isMaxTest=df.resultJointTest[,11],isChiStd=df.resultJointTest[,12])
df.coverage %>% gt()

df.coverage_0_500 <- df.coverage[(df.coverage$cov == 0),c(1,3:7,9)]
df.coverage_5_500 <- df.coverage[(df.coverage$cov == 0.5),c(1,3:7,9)]
df.coverage_9_500 <- df.coverage[(df.coverage$cov == 0.9),c(1,3:7,9)]

df.coverage_both <- df.coverage

#table_latex <- df.coverage[(df.coverage$cov == 0.9),c(1,3:7,9)] %>% gt() %>% as_latex() %>% as.character()
#print(table_latex)


rm(list = ls()[(ls() != "df.coverage_0_500") & (ls() != "df.coverage_5_500") & (ls() != "df.coverage_9_500") & ls() != "df.coverage_both"])
load("./workSpaceMCJointTest_full_coverage_n1000.RData")
df.coverage_both <- rbind(df.coverage,df.coverage_both)
df.resultJointTest <- df.resultJointTest[df.resultJointTest$vec.xjumpReportSpec == 0,]
df.coverage <- data.frame(n=df.resultJointTest[,5],cov=df.resultJointTest[,3],dim=df.resultJointTest[,4],p.naive=df.resultJointTest[,8],p.bonferroni=df.resultJointTest[,9],p.joint=df.resultJointTest[,10],isMaxTest=df.resultJointTest[,11],isChiStd=df.resultJointTest[,12])
df.coverage %>% gt()
df.coverage_0_1000 <- df.coverage[(df.coverage$cov == 0),c(1,3:7,9)]
df.coverage_5_1000 <- df.coverage[(df.coverage$cov == 0.5),c(1,3:7,9)]
df.coverage_9_1000 <- df.coverage[(df.coverage$cov == 0.9),c(1,3:7,9)]


df.show <- data.frame()
for (i in 1:5) {
  df.show_tmp <- data.frame(dim=df.coverage_0_500[1+(i-1)*3,2],naive_5=df.coverage_0_500[1+(i-1)*3,3],bonfe_5=df.coverage_0_500[1+(i-1)*3,4],chisq5=df.coverage_0_500[2+(i-1)*3,5],max5=df.coverage_0_500[1+(i-1)*3,5],chisq_std5=df.coverage_0_500[3+(i-1)*3,5])
  df.result <- data.frame(naive_10=df.coverage_0_1000[1+(i-1)*3,3],bonfe_10=df.coverage_0_1000[1+(i-1)*3,4],chisq10=df.coverage_0_1000[2+(i-1)*3,5],max10=df.coverage_0_1000[1+(i-1)*3,5],chisq_std10=df.coverage_0_1000[3+(i-1)*3,5])
  df.show_tmp <- cbind(df.show_tmp,df.result)
  df.show <- rbind(df.show,df.show_tmp)
}
table_latex <- df.show %>% gt() %>% as_latex() %>% as.character()
print(table_latex)

df.show <- data.frame()
for (i in 1:5) {
  df.show_tmp <- data.frame(dim=df.coverage_5_500[1+(i-1)*3,2],naive_5=df.coverage_5_500[1+(i-1)*3,3],bonfe_5=df.coverage_5_500[1+(i-1)*3,4],chisq5=df.coverage_5_500[2+(i-1)*3,5],max5=df.coverage_5_500[1+(i-1)*3,5],chisq_std5=df.coverage_5_500[3+(i-1)*3,5])
  df.result <- data.frame(naive_10=df.coverage_5_1000[1+(i-1)*3,3],bonfe_10=df.coverage_5_1000[1+(i-1)*3,4],chisq10=df.coverage_5_1000[2+(i-1)*3,5],max10=df.coverage_5_1000[1+(i-1)*3,5],chisq_std10=df.coverage_5_1000[3+(i-1)*3,5])
  df.show_tmp <- cbind(df.show_tmp,df.result)
  df.show <- rbind(df.show,df.show_tmp)
}

table_latex <- df.show %>% gt() %>% as_latex() %>% as.character()
print(table_latex)

df.show <- data.frame()
for (i in 1:5) {
  df.show_tmp <- data.frame(dim=df.coverage_9_500[1+(i-1)*3,2],naive_5=df.coverage_9_500[1+(i-1)*3,3],bonfe_5=df.coverage_9_500[1+(i-1)*3,4],chisq5=df.coverage_9_500[2+(i-1)*3,5],max5=df.coverage_9_500[1+(i-1)*3,5],chisq_std5=df.coverage_9_500[3+(i-1)*3,5])
  df.result <- data.frame(naive_10=df.coverage_9_1000[1+(i-1)*3,3],bonfe_10=df.coverage_9_1000[1+(i-1)*3,4],chisq10=df.coverage_9_1000[2+(i-1)*3,5],max10=df.coverage_9_1000[1+(i-1)*3,5],chisq_std10=df.coverage_9_1000[3+(i-1)*3,5])
  df.show_tmp <- cbind(df.show_tmp,df.result)
  df.show <- rbind(df.show,df.show_tmp)
}
table_latex <- df.show %>% gt() %>% as_latex() %>% as.character()
print(table_latex)

rm(list = ls()[(ls() != "df.coverage_0_500") & (ls() != "df.coverage_5_500") & (ls() != "df.coverage_9_500") & ls() != "df.coverage_both"])
load("./workSpaceMCJointTest_full_coverage_n500_dim1.RData")
df.coverage_both <- rbind(df.coverage,df.coverage_both)

rm(list = ls()[(ls() != "df.coverage_0_500") & (ls() != "df.coverage_5_500") & (ls() != "df.coverage_9_500") & ls() != "df.coverage_both"])
load("./workSpaceMCJointTest_full_coverage_n1000_dim1.RData")
df.coverage_both <- rbind(df.coverage,df.coverage_both)
```

# Joint Tests generating RDatas
```{r Joint Test Run alternative 1}
rm(list = ls()[ls()!="df.coverage_both"])
library(tictoc)
library(rdtest)
library(gt)
library(dplyr)
library(truncnorm)

fun.runnerJoint = function(str.spec)
{
  message(str.spec)
  tic(str.spec)
  time.start <- Sys.time()
  eval(parse(text = paste0(paste0("list.summary <- rdtest::return_result_MC_joint(",str.spec),")")))
  time.end <- Sys.time()
  #toc()
  message((time.end - time.start)," min")
  return(list.summary)
}

# Specification list
# values for x jumps
vec.xJump <- c(0.15,0.3)
# values for z jumps
vec.zJump <- seq(0,2,length=5)
# sample sizes
vec.n <- c(500,1000)
vec.covZ <- c(0.5)
vec.dimZ <- c(1,3,5)
# the last one, half, full:
## half: for 3, 2:3 jumps.
vec.frac_jump <- list("'Last'","'Half'","'All'")

int.numberSpec <- length(vec.xJump)*length(vec.n)*length(vec.zJump)*length(vec.covZ)*length(vec.dimZ)*2*length(vec.frac_jump)


vec.effNzReportSpec <- c(1:int.numberSpec)
vec.effNxReportSpec <- c(1:int.numberSpec)
vec.corZReportSpec <- c(1:int.numberSpec)
vec.dimVecReportSpec <- c(1:int.numberSpec)
vec.nReportSpec <- c(1:int.numberSpec)
vec.xjumpReportSpec <- c(1:int.numberSpec)
vec.zjumpReportSpec <- c(1:int.numberSpec)
vec.naiveReportResult <- c(1:int.numberSpec)
vec.bonfeReportResult <- c(1:int.numberSpec)
vec.jointReportResult <- c(1:int.numberSpec)
vec.maxTestSpec <- c(1:int.numberSpec)
vec.avgMaxTestCritical <- c(1:int.numberSpec)
vec.medianMaxTestCritical <- c(1:int.numberSpec)
vec.jumpTestSpec <- c(1:int.numberSpec)

list.speclist <- list()

counter <- 1
df.resultJointTest <- data.frame()
fun.repeaterJoint <- function(n,cov_z,dim,x_jump,z_jump,bool_max_test,bool_L2_std = FALSE,counter,df.resultJointTest,frac_jump,spec) {
    list.sum <- fun.runnerJoint(str.spec=spec)

    real.effNzReportSpec <- round(list.sum$effN.mean,1)
    real.effNxReportSpec <- round(list.sum$effNx.mean,1)
    real.corZReportSpec <- round(list.sum$cor.z,2)
    real.dimVecReportSpec <- dim
    real.nReportSpec <- n
    real.xjumpReportSpec <- x_jump
    real.zjumpReportSpec <- z_jump

    real.naiveReportResult <- round(list.sum$naive,3)
    real.bonfeReportResult <- round(list.sum$bonfe,3)
    real.jointReportResult <- round(list.sum$joint,3)
    real.maxTestSpec <- bool_max_test
    if (bool_max_test) {
      real.avgMaxTestCritical <- round(mean(list.sum$maxCritical),3)
      real.medianMaxTestCritical <- round(median(list.sum$maxCritical),3)
    } else {
      real.avgMaxTestCritical <- NA
      real.medianMaxTestCritical <- NA
    }

    list.speclist[counter] <- spec
    #print(spec)
    df.resultJointTest <- rbind(df.resultJointTest,
                                 data.frame(vec.effNzReportSpec = real.effNzReportSpec,
                                 vec.effNxReportSpec = real.effNxReportSpec,
                                 vec.corZReportSpec = cov_z,
                                 vec.dimVecReportSpec = real.dimVecReportSpec,
                                 vec.nReportSpec = real.nReportSpec,
                                 vec.xjumpReportSpec = real.xjumpReportSpec,
                                 vec.zjumpReportSpec = real.zjumpReportSpec,
                                 vec.naiveReportResult = real.naiveReportResult,
                                 vec.bonfeReportResult = real.bonfeReportResult,
                                 vec.jointReportResult = real.jointReportResult,
                                 vec.maxTestSpec = real.maxTestSpec,
                                 vec.chisqStd = bool_L2_std,
                                 vec.avgMaxTestCritical = real.avgMaxTestCritical,
                                 vec.medianMaxTestCritical = real.medianMaxTestCritical,
                                 vec.jumpTestSpec = frac_jump))
    return(df.resultJointTest)
}

#
# UNDO COMMENT OUT TO RE-GENERATE THE RESULTS
#
for (n in vec.n) {
  for (dim in vec.dimZ) {
    for (cov_z in vec.covZ) {
      for (frac_jump in vec.frac_jump) {
        cat("Running for n=",n,",dim=",dim,",cov_z=",cov_z,",frac=", frac_jump,".\n")
        # bool_max_test TRUE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",TRUE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = TRUE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec)
                counter <- counter + 1
            }
          }
        }
        # bool_max_test FALSE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",FALSE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = FALSE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec)
                counter <- counter + 1
            }
          }
        }
        # bool_max_test FALSE, bool_L2_std TRUE
        for (x_jump in vec.xJump) {
          for (z_jump in vec.zJump) {
            if ((x_jump > 0.000001) | (x_jump == 0 & z_jump == 0)) {
                spec <- paste0("int_ns=",3000,",a_2=",0,",x_jump=",x_jump,",jump=",z_jump,",dim=",dim,",n=",n,",cov_z =", cov_z,",frac_jump=",frac_jump,",bool_mutePrint=TRUE,bool_max_test=",FALSE,",bool_L2_std=",TRUE)
                df.resultJointTest <- fun.repeaterJoint(n = n,cov_z = cov_z,dim = dim,x_jump = x_jump,z_jump = z_jump,bool_max_test = FALSE,counter = counter,df.resultJointTest = df.resultJointTest,frac_jump = frac_jump,spec = spec,bool_L2_std=TRUE)
                counter <- counter + 1
            }
          }
        }
      cat("Saving the workspace upto... n=",n,",dim=",dim,",cov_z=",cov_z,",frac=",frac_jump,".\n")
      save.image("./workSpaceMCJointTest_full_part.RData")
      }
    }
  }
  if (n == 500) {
    save.image("./workSpaceMCJointTest_full_power_n500.RData")
    df.resultJointTest <- data.frame()
  }
}
save.image("./workSpaceMCJointTest_full_power_n1000.RData")


```

## plots
```{r}
rm(list = ls()[ls()!="df.coverage_both"])
load("./workSpaceMCJointTest_full_power_n500.RData")
df.resultJointTest[,c(3,4,6:11,13)]

df.resultNull <- df.resultJointTest[df.resultJointTest$vec.xjumpReportSpec == 0,]
df.resultNull[,c(3,4,8:11,13,15)]

for (n in c(500))
{
  for (dim in unique(df.resultJointTest$vec.dimVecReportSpec))
  {
    for (cor in c(0.5))
    {
      for (xval in unique(df.resultJointTest$vec.xjumpReportSpec))
      {
        for (jumpTest in list("'Last'","'Half'","'All'")) {
          df.resultEval <- df.resultJointTest[df.resultJointTest$vec.dimVecReportSpec==dim
                                            & df.resultJointTest$vec.corZReportSpec == cor
                                            & df.resultJointTest$vec.nReportSpec== n
                                            & df.resultJointTest$vec.xjumpReportSpec == xval
                                            & df.resultJointTest$vec.jumpTestSpec == jumpTest
                                            & df.resultJointTest$vec.maxTestSpec == TRUE,]
          #df.resultEvalMat <- rbind(data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.jointReportResult,type="joint max"),data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.naiveReportResult,type="naive"))
          df.resultEvalMat <- rbind(data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.jointReportResult,type="Max",shape="2"),data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.bonfeReportResult,type="Bonferroni",shape="1"))
          
          df.resultEvalMat <- rbind(df.resultEvalMat,data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.bonfeReportResult,type="Bonferroni",shape="2"))
          df.resultEvalChiStd <- df.resultJointTest[df.resultJointTest$vec.dimVecReportSpec==dim
                                            & df.resultJointTest$vec.corZReportSpec == cor
                                            & df.resultJointTest$vec.nReportSpec== n
                                            & df.resultJointTest$vec.xjumpReportSpec == xval
                                            & df.resultJointTest$vec.jumpTestSpec == jumpTest
                                            & df.resultJointTest$vec.maxTestSpec == FALSE
                                            & df.resultJointTest$vec.chisqStd == TRUE,]
          df.resultEvalMat <- rbind(df.resultEvalMat,data.frame(z=df.resultEvalChiStd$vec.zjumpReportSpec,prob=df.resultEvalChiStd$vec.jointReportResult,type="sWald",shape="5"))
          df.resultEvalMat$case <- "alternative"
          
          p_2 <- ggplot(data = df.resultEvalMat, mapping = aes(x = z, y = prob,color=type,shape = type)) + geom_line() + geom_point(size=3) +
            scale_y_continuous(breaks=c(0,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1),position = "right") +
            geom_vline(xintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 0.05, linetype = "dashed", size = 0.5) +
            geom_hline(yintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 1, linetype = "dashed", size = 0.01) + 
            ggtitle("") + ylab("Rejection probability") +
            xlab(paste0("Jump in z, p = ",0.5+xval/2)) + 
            theme(legend.title=element_blank()) + 
            theme(legend.position = "top") +
            theme(text = element_text(size = 17))

          df.coverageMat <-
            rbind(
              data.frame(
                z = 0,
                prob = df.coverage_both[df.coverage_both$n == n &
                                        df.coverage_both$dim == dim &
                                        df.coverage_both$cov == cor &
                                        df.coverage_both$isMaxTest == FALSE &
                                        df.coverage_both$isChiStd == FALSE,
                                        ]$p.bonferroni,
                type = "B",
                case = "null",
                shape = "1"
              ),
              data.frame(
                z = 0,
                prob = df.coverage_both[df.coverage_both$n == n &
                                        df.coverage_both$dim == dim &
                                        df.coverage_both$cov == cor &
                                        df.coverage_both$isMaxTest == TRUE &
                                        df.coverage_both$isChiStd == FALSE,
                                        ]$p.joint,
                type = "M",
                case = "null",
                shape = "2"
              ),
              data.frame(
                z = 0,
                prob = df.coverage_both[df.coverage_both$n == n &
                                        df.coverage_both$dim == dim &
                                        df.coverage_both$cov == cor &
                                        df.coverage_both$isMaxTest == FALSE &
                                        df.coverage_both$isChiStd == TRUE,
                                        ]$p.joint,
                type = "W",
                case = "null",
                shape = "5"
              )
            )
      
          p_null <- ggplot(data = df.coverageMat, mapping = aes(x = z, y = prob,color=type,shape=type)) + geom_point(size=3) +
            scale_y_continuous(breaks=c(0,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
            geom_vline(xintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 0.05, linetype = "dashed", size = 0.5) +
            geom_hline(yintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 1, linetype = "dashed", size = 0.01) + 
            ggtitle("") + ylab("Coverage probability") + xlab("Null") +
            scale_x_continuous(breaks=c(0)) + 
            theme(legend.title=element_blank()) + 
            theme(legend.position = "top") +
            theme(text = element_text(size = 17))
            #theme(legend.title=element_blank())
          p_joint <- ggpubr::ggarrange(p_null,p_2, widths = c(1,2))#, common.legend=TRUE)
          print(p_joint)
          file_path <- paste0("./plots/n_",n,"_dim_",dim,"_pval_",0.5+xval/2,"_corr_",cor,"_alt_",jumpTest,".png")
          ggsave(file=file_path,
             p_joint,
             device="png")
        }
      }
    }
  }
}

rm(list = ls()[ls()!="df.coverage_both"])
load("./workSpaceMCJointTest_full_power_n1000.RData")
df.resultJointTest[,c(3,4,6:11)]

df.resultNull <- df.resultJointTest[df.resultJointTest$vec.xjumpReportSpec == 0,]
df.resultNull[,c(3,4,8:11,14)]

for (n in c(1000))
{
  for (dim in unique(df.resultJointTest$vec.dimVecReportSpec))
  {
    for (cor in c(0.5))
    {
      for (xval in unique(df.resultJointTest$vec.xjumpReportSpec))
      {
        for (jumpTest in list("'Last'","'Half'","'All'")) {
          df.resultEval <- df.resultJointTest[df.resultJointTest$vec.dimVecReportSpec==dim
                                            & df.resultJointTest$vec.corZReportSpec == cor
                                            & df.resultJointTest$vec.nReportSpec== n
                                            & df.resultJointTest$vec.xjumpReportSpec == xval
                                            & df.resultJointTest$vec.jumpTestSpec == jumpTest
                                            & df.resultJointTest$vec.maxTestSpec == TRUE,]
          #df.resultEvalMat <- rbind(data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.jointReportResult,type="joint max"),data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.naiveReportResult,type="naive"))
          df.resultEvalMat <- rbind(data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.jointReportResult,type="Max",shape="2"),data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.bonfeReportResult,type="Bonferroni",shape="1"))
          
          df.resultEvalMat <- rbind(df.resultEvalMat,data.frame(z=df.resultEval$vec.zjumpReportSpec,prob=df.resultEval$vec.bonfeReportResult,type="Bonferroni",shape="2"))
          df.resultEvalChiStd <- df.resultJointTest[df.resultJointTest$vec.dimVecReportSpec==dim
                                            & df.resultJointTest$vec.corZReportSpec == cor
                                            & df.resultJointTest$vec.nReportSpec== n
                                            & df.resultJointTest$vec.xjumpReportSpec == xval
                                            & df.resultJointTest$vec.jumpTestSpec == jumpTest
                                            & df.resultJointTest$vec.maxTestSpec == FALSE
                                            & df.resultJointTest$vec.chisqStd == TRUE,]
          df.resultEvalMat <- rbind(df.resultEvalMat,data.frame(z=df.resultEvalChiStd$vec.zjumpReportSpec,prob=df.resultEvalChiStd$vec.jointReportResult,type="sWald",shape="5"))
          df.resultEvalMat$case <- "alternative"
          
          p_2 <- ggplot(data = df.resultEvalMat, mapping = aes(x = z, y = prob,color=type,shape = type)) + geom_line() + geom_point(size=3) +
            scale_y_continuous(breaks=c(0,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1),position = "right") +
            geom_vline(xintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 0.05, linetype = "dashed", size = 0.5) +
            geom_hline(yintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 1, linetype = "dashed", size = 0.01) + 
            ggtitle("") + ylab("Rejection probability") +
            xlab(paste0("Jump in z, p = ",0.5+xval/2)) + 
            theme(legend.title=element_blank()) + 
            theme(legend.position = "top") +
            theme(text = element_text(size = 17))

          df.coverageMat <-
            rbind(
              data.frame(
                z = 0,
                prob = df.coverage_both[df.coverage_both$n == n &
                                        df.coverage_both$dim == dim &
                                        df.coverage_both$cov == cor &
                                        df.coverage_both$isMaxTest == FALSE &
                                        df.coverage_both$isChiStd == FALSE,
                                        ]$p.bonferroni,
                type = "B",
                case = "null",
                shape = "1"
              ),
              data.frame(
                z = 0,
                prob = df.coverage_both[df.coverage_both$n == n &
                                        df.coverage_both$dim == dim &
                                        df.coverage_both$cov == cor &
                                        df.coverage_both$isMaxTest == TRUE &
                                        df.coverage_both$isChiStd == FALSE,
                                        ]$p.joint,
                type = "M",
                case = "null",
                shape = "2"
              ),
              data.frame(
                z = 0,
                prob = df.coverage_both[df.coverage_both$n == n &
                                        df.coverage_both$dim == dim &
                                        df.coverage_both$cov == cor &
                                        df.coverage_both$isMaxTest == FALSE &
                                        df.coverage_both$isChiStd == TRUE,
                                        ]$p.joint,
                type = "W",
                case = "null",
                shape = "5"
              )
            )
      
          p_null <- ggplot(data = df.coverageMat, mapping = aes(x = z, y = prob,color=type,shape=type)) + geom_point(size=3) +
            scale_y_continuous(breaks=c(0,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
            geom_vline(xintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 0.05, linetype = "dashed", size = 0.5) +
            geom_hline(yintercept = 0, linetype = "dashed", size = 0.1) +
            geom_hline(yintercept = 1, linetype = "dashed", size = 0.01) + 
            ggtitle("") + ylab("Coverage probability") + xlab("Null") +
            scale_x_continuous(breaks=c(0)) + 
            theme(legend.title=element_blank()) + 
            theme(legend.position = "top") + 
            theme(text = element_text(size = 17))
            #theme(legend.title=element_blank())
          p_joint <- ggpubr::ggarrange(p_null,p_2, widths = c(1,2))#, common.legend=TRUE) 
          print(p_joint)
          file_path <- paste0("./plots/n_",n,"_dim_",dim,"_pval_",0.5+xval/2,"_corr_",cor,"_alt_",jumpTest,".png")
          ggsave(file=file_path,
             p_joint,
             device="png")
        }
      }
    }
  }
}

```
